### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/reneri#5]
```
[ERROR] Failed to execute goal on project reneri: Could not resolve dependencies for project eu.stamp-project:reneri:maven-plugin:1.0-EXPERIMENTS: Could not find artifact eu.stamp-project:descartes:jar:1.2.5-EXPERIMENTS in inria (http://maven.inria.fr/artifactory/triskell-public-release)
```

Should we change the version, deploy something or add another repository to pom?

**Comment by oscarlvp** [comment]
You can change the version to 1.2.5 or compile and use this release: https://github.com/STAMP-project/pitest-descartes/releases/tag/1.2.5-EXPERIMENTS

**Comment by monperrus** [comment]
Disagree, we want to change the pom, compiling has to work out of the box :-)

**Comment by oscarlvp** [comment]
So, change the pom to use 1.2.5
1.2.5-EXPERIMENTS is the version used for the paper. 
1.2.5 has a different PIT version, but you can use it.
Reneri uses Descartes only to mutate the code. It does not use PIT.
First Reneri stable release should use 1.2.6.
The replication package for the paper should contain all compiled artifacts.
